git:
  username:
  token: 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
  repository: https://github.com/wso2-enterprise/migration-docs
  directory: migration-docs
  organization: wso2-enterprise
doc:
  product: APIM
  source: 3.1.0
  target: 4.1.0
  dependency: isaskm