git:
  username:
  token:
  repository: https://github.com/wso2-enterprise/migration-docs
  directory: migration-docs
  organization: wso2-enterprise
wso2:
  product: APIM
  source: 3.2.0
  target: 4.1.0
  dependency:
